---
- name: Installing Terraform for Debian type OS family (using apt)
  include_tasks: debian.yaml
  when: ansible_facts['os_family'] == "Debian"

# supported Debian and Ubuntu releases
# https://www.terraform.io/docs/cli/install/apt.html#supported-debian-and-ubuntu-releases

# jessie
# stretch
# buster

# xenial
# bionic
# eoam
# focal
# groovy
